<a href="https://colab.research.google.com/github/ivannarch865/ivannarichards5to/blob/main/A4_Pivot_Tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
file_path_antro= 'https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/antropometria-dataset.csv'
import pandas as pd
import numpy as np
df_antropometria=pd.read_csv(file_path_antro)
df_antropometria.head()

,folio,intp,entidad,desc_ent,sexo,edad,meses,peso,ropa,talla,...,hpresion,tbrazo,htension,PrimaryLast,code_upm,est_dis,est_urb,est_marg,pondef,est_var
0,210295,2,21,PUEBLA,2,38,8,73.70,2,146.4,...,16:30,2,16:35,1,R2101,5,3,1,3470.002176,215
1,101655,3,10,DURANGO,2,11,11,35.65,2,145.1,...,15:25,3,15:25,1,M1041,1,1,1,417.946672,101
2,10287,6,1,AGUASCALIENTES,2,18,8,54.80,1,162.0,...,9:40,1,9:40,1,M0108,5,3,1,472.980811,15
3,91526,4,9,DISTRITO FEDERAL,1,10,8,33.40,2,146.5,...,7:40,3,7:45,1,M0931,4,3,2,1832.581391,94
4,210939,3,21,PUEBLA,2,19,3,97.95,2,161.0,...,6:00,2,6:00,1,M2123,5,3,1,7622.066564,215

#1. Average weight of people from MORELOS

In [14]:

df1= pd.pivot_table (
    df_antropometria,
     index="desc_ent",
     values="peso",
     aggfunc="mean")

df1

                                      peso
desc_ent
AGUASCALIENTES                   66.357786
BAJA CALIFORNIA                  68.467270
BAJA CALIFORNIA SUR              71.809198
CAMPECHE                         65.418475
CHIAPAS                          57.613775
CHIHUAHUA                        66.656005
COAHUILA DE ZARAGOZA             68.154142
COLIMA                           68.743648
DISTRITO FEDERAL                 65.119273
DURANGO                          66.354922
GUANAJUATO                       63.936390
GUERRERO                         60.466315
HIDALGO                          59.995917
JALISCO                          66.697270
MEXICO                           60.680850
MICHOACAN DE OCAMPO              64.900000
MORELOS                          63.541295
NAYARIT                          66.541827
NUEVO LEON                       67.239853
OAXACA                           58.800067
PUEBLA                           60.102996
QUERETARO                        63.547342
QUINTANA ROO                     64.238904
SAN LUIS POTOSI                  60.576912
SINALOA                          68.051272
SONORA                           68.849473
TABASCO                          66.554701
TAMAULIPAS                       68.210911
TLAXCALA                         62.085398
VERACRUZ DE IGNACIO DE LA LLAVE  62.546117
YUCATAN                          62.706315
ZACATECAS                        64.238524

In [15]:
df1.loc["MORELOS", :]

peso    63.541295
Name: MORELOS, dtype: float64

# 2. Median Weight of Sex 2 Yucatan

In [24]:
df2= pd.pivot_table (
    df_antropometria,
     index="desc_ent",
     columns="sexo",
     values="peso",
     aggfunc="median")

df2

sexo                                   1        2
desc_ent
AGUASCALIENTES                   69.9500  63.7000
BAJA CALIFORNIA                  70.6500  64.2000
BAJA CALIFORNIA SUR              76.6500  68.5500
CAMPECHE                         67.3500  62.3750
CHIAPAS                          59.2000  56.0250
CHIHUAHUA                        69.3000  64.6250
COAHUILA DE ZARAGOZA             68.3000  67.3000
COLIMA                           71.7000  66.0000
DISTRITO FEDERAL                 69.0000  61.4500
DURANGO                          70.3500  62.5000
GUANAJUATO                       65.0625  60.3250
GUERRERO                         60.5000  57.2000
HIDALGO                          63.3000  57.9000
JALISCO                          65.5875  63.3500
MEXICO                           62.4500  56.9500
MICHOACAN DE OCAMPO              67.6250  63.4000
MORELOS                          65.2000  61.4500
NAYARIT                          69.0500  63.7000
NUEVO LEON                       69.4000  65.1000
OAXACA                           59.5500  56.8000
PUEBLA                           61.8750  59.5500
QUERETARO                        65.2750  59.4500
QUINTANA ROO                     65.9250  60.8500
SAN LUIS POTOSI                  62.2000  57.4500
SINALOA                          71.1000  64.3000
SONORA                           72.3000  66.6500
TABASCO                          69.7500  62.6000
TAMAULIPAS                       72.7500  63.3500
TLAXCALA                         64.2750  59.8750
VERACRUZ DE IGNACIO DE LA LLAVE  64.3000  59.4725
YUCATAN                          66.0000  59.5750
ZACATECAS                        65.3000  61.6250

In [25]:
df2.loc["YUCATAN", "2":]

sexo
2    59.575
Name: YUCATAN, dtype: float64

#3. State [X] has the lowest average peso (weight) of sex1.

In [49]:
df3= pd.pivot_table (
    df_antropometria,
     index="desc_ent",
     columns="sexo",
     values="peso",
     aggfunc="mean")

df3

sexo                                     1          2
desc_ent
AGUASCALIENTES                   69.985381  63.254292
BAJA CALIFORNIA                  71.391818  65.893667
BAJA CALIFORNIA SUR              75.561015  68.168959
CAMPECHE                         68.622637  62.920493
CHIAPAS                          58.365222  57.096111
CHIHUAHUA                        68.892642  64.815295
COAHUILA DE ZARAGOZA             68.873094  67.467348
COLIMA                           70.998878  66.978393
DISTRITO FEDERAL                 69.460661  61.654128
DURANGO                          68.846451  64.400031
GUANAJUATO                       65.008000  63.100995
GUERRERO                         62.611437  58.899850
HIDALGO                          61.747958  58.972554
JALISCO                          67.076482  66.418111
MEXICO                           63.140314  58.887882
MICHOACAN DE OCAMPO              66.374612  63.784311
MORELOS                          65.741943  62.195391
NAYARIT                          68.822143  64.890564
NUEVO LEON                       70.168106  64.823014
OAXACA                           60.810332  57.450557
PUEBLA                           61.866875  58.820175
QUERETARO                        66.751233  60.860793
QUINTANA ROO                     65.149528  63.538000
SAN LUIS POTOSI                  62.614907  58.979163
SINALOA                          71.122911  65.565234
SONORA                           70.880406  67.024857
TABASCO                          69.255801  64.190187
TAMAULIPAS                       72.060601  64.866851
TLAXCALA                         64.784437  60.201164
VERACRUZ DE IGNACIO DE LA LLAVE  65.324094  60.565646
YUCATAN                          65.717541  60.537515
ZACATECAS                        66.096483  62.757788

In [50]:
ndf3=df3.loc[:,:1]
ndf3

sexo                                     1
desc_ent
AGUASCALIENTES                   69.985381
BAJA CALIFORNIA                  71.391818
BAJA CALIFORNIA SUR              75.561015
CAMPECHE                         68.622637
CHIAPAS                          58.365222
CHIHUAHUA                        68.892642
COAHUILA DE ZARAGOZA             68.873094
COLIMA                           70.998878
DISTRITO FEDERAL                 69.460661
DURANGO                          68.846451
GUANAJUATO                       65.008000
GUERRERO                         62.611437
HIDALGO                          61.747958
JALISCO                          67.076482
MEXICO                           63.140314
MICHOACAN DE OCAMPO              66.374612
MORELOS                          65.741943
NAYARIT                          68.822143
NUEVO LEON                       70.168106
OAXACA                           60.810332
PUEBLA                           61.866875
QUERETARO                        66.751233
QUINTANA ROO                     65.149528
SAN LUIS POTOSI                  62.614907
SINALOA                          71.122911
SONORA                           70.880406
TABASCO                          69.255801
TAMAULIPAS                       72.060601
TLAXCALA                         64.784437
VERACRUZ DE IGNACIO DE LA LLAVE  65.324094
YUCATAN                          65.717541
ZACATECAS                        66.096483

In [51]:
ndf3=ndf3.sort_values(by=1, ascending=True)
ndf3

sexo                                     1
desc_ent
CHIAPAS                          58.365222
OAXACA                           60.810332
HIDALGO                          61.747958
PUEBLA                           61.866875
GUERRERO                         62.611437
SAN LUIS POTOSI                  62.614907
MEXICO                           63.140314
TLAXCALA                         64.784437
GUANAJUATO                       65.008000
QUINTANA ROO                     65.149528
VERACRUZ DE IGNACIO DE LA LLAVE  65.324094
YUCATAN                          65.717541
MORELOS                          65.741943
ZACATECAS                        66.096483
MICHOACAN DE OCAMPO              66.374612
QUERETARO                        66.751233
JALISCO                          67.076482
CAMPECHE                         68.622637
NAYARIT                          68.822143
DURANGO                          68.846451
COAHUILA DE ZARAGOZA             68.873094
CHIHUAHUA                        68.892642
TABASCO                          69.255801
DISTRITO FEDERAL                 69.460661
AGUASCALIENTES                   69.985381
NUEVO LEON                       70.168106
SONORA                           70.880406
COLIMA                           70.998878
SINALOA                          71.122911
BAJA CALIFORNIA                  71.391818
TAMAULIPAS                       72.060601
BAJA CALIFORNIA SUR              75.561015

In [52]:
ndf3.iloc[:1, :]

sexo              1
desc_ent
CHIAPAS   58.365222

#4. What is the average age of Never-married with Bachelors?

In [53]:
file_path_adult= 'https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/adult.csv'
df_adult=pd.read_csv(file_path_adult)
df_adult.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,the label
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [54]:
df4= pd.pivot_table (
    df_adult,
     index="marital-status",
     columns="education",
     values="age",
     aggfunc="mean")

df4

education,10th,11th,12th,1st-4th,5th-6th,7th-8th,9th,Assoc-acdm,Assoc-voc,Bachelors,Doctorate,HS-grad,Masters,Preschool,Prof-school,Some-college
marital-status,,,,,,,,,,,,,,,,
Divorced,44.133333,41.230769,41.333333,62.700000,53.700000,49.452055,46.281250,41.064039,40.653846,44.243590,49.303030,42.363918,47.278970,36.000000,44.127273,42.327409
Married-AF-spouse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.500000,29.000000,30.750000,NaN,34.615385,NaN,NaN,NaN,27.333333
Married-civ-spouse,46.126074,42.559322,41.892308,47.888889,45.872093,50.601671,45.886957,40.617391,40.719884,42.648121,48.786713,42.817131,45.154536,48.150000,46.560680,42.210433
Married-spouse-absent,42.000000,34.052632,38.000000,41.416667,42.650000,49.285714,36.666667,44.750000,45.538462,41.352941,45.571429,39.413223,47.941176,44.750000,51.333333,37.289474
Never-married,23.961219,22.261092,23.206897,31.717949,30.651685,34.035398,28.225806,29.311573,30.071823,30.511978,41.739726,28.533506,37.821782,35.409091,36.344086,25.677804
Separated,39.530612,36.937500,36.000000,49.777778,43.722222,41.478261,43.606061,39.633333,40.738095,42.130435,42.857143,38.266010,44.200000,48.000000,44.000000,38.086364
Widowed,59.256410,55.973684,60.600000,62.588235,67.785714,62.968750,62.826087,52.130435,60.829268,55.475610,65.000000,59.405797,58.341463,58.666667,55.600000,57.523256
test_category_female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.000000,NaN,NaN,NaN,NaN
test_category_male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.000000,NaN,NaN,NaN,NaN

In [61]:
df4.columns

Index([' 10th', ' 11th', ' 12th', ' 1st-4th', ' 5th-6th', ' 7th-8th', ' 9th',
       ' Assoc-acdm', ' Assoc-voc', ' Bachelors', ' Doctorate', ' HS-grad',
       ' Masters', ' Preschool', ' Prof-school', ' Some-college'],
      dtype='object', name='education')

In [67]:
df4.loc[' Never-married', ' Bachelors']

np.float64(30.51197771587744)

#5. Median `Age` of `Female` `Divorced` with education `12th`

In [70]:
df_adult.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'the label'],
      dtype='object')

In [79]:
df5 = pd.pivot_table(
    df_adult,
    index=['education', "marital-status"],
    columns="sex",
    values="age",
    aggfunc="median"
)

df5

sex                                 Female  Male
education    marital-status
10th         Divorced                 45.0  39.0
             Married-civ-spouse       32.0  48.0
             Married-spouse-absent    39.0  49.0
             Never-married            18.0  20.0
             Separated                34.0  38.0
...                                    ...   ...
Some-college Married-civ-spouse       38.0  42.0
             Married-spouse-absent    31.0  37.0
             Never-married            22.0  23.0
             Separated                38.0  37.0
             Widowed                  58.0  60.5

[103 rows x 2 columns]

In [81]:
df5.index

MultiIndex([(        ' 10th',              ' Divorced'),
            (        ' 10th',    ' Married-civ-spouse'),
            (        ' 10th', ' Married-spouse-absent'),
            (        ' 10th',         ' Never-married'),
            (        ' 10th',             ' Separated'),
            (        ' 10th',               ' Widowed'),
            (        ' 11th',              ' Divorced'),
            (        ' 11th',    ' Married-civ-spouse'),
            (        ' 11th', ' Married-spouse-absent'),
            (        ' 11th',         ' Never-married'),
            ...
            ( ' Prof-school',         ' Never-married'),
            ( ' Prof-school',             ' Separated'),
            ( ' Prof-school',               ' Widowed'),
            (' Some-college',              ' Divorced'),
            (' Some-college',     ' Married-AF-spouse'),
            (' Some-college',    ' Married-civ-spouse'),
            (' Some-college', ' Married-spouse-absent'),
            (' Some-college',         ' Never-married'),
            (' Some-college',             ' Separated'),
            (' Some-college',               ' Widowed')],
           names=['education', 'marital-status'], length=103)

In [82]:
ndf5= df5.loc[" 10th", " Female":]
ndf5

sex                    Female  Male
marital-status
Divorced                 45.0  39.0
Married-civ-spouse       32.0  48.0
Married-spouse-absent    39.0  49.0
Never-married            18.0  20.0
Separated                34.0  38.0
Widowed                  60.0  57.0

In [89]:
mdf5= df5.loc[" 12th", :" Female"]
mdf5

sex                    Female
marital-status
Divorced                 41.0
Married-civ-spouse       34.0
Married-spouse-absent    25.5
Never-married            18.0
Separated                35.0
Widowed                  56.0

In [90]:
ldf5=mdf5.loc[" Divorced", :]
ldf5

sex
Female    41.0
Name:  Divorced, dtype: float64