<a href="https://colab.research.google.com/github/ivannarch865/ivannarichards5to/blob/main/Class3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd
import numpy as np

In [78]:
x= {"Company": ["Ford","Ford", "VW", "BMW","Cooper","Cooper",None],
    "Stars":[1, 2, np.nan , 2, 1, 1,None],
    "Weight":[2,2,4,2,3,None,None],
    "Origin":["China", "Mexico", "Mexico", None, "China", np.nan,None],
    "Length":[40,50,30,np.nan,45, pd.NaT,None],
    "Nones": [None, None, None, None, None, None, None]}

df= pd.DataFrame(data=x)
df.head(20)

  Company  Stars  Weight  Origin Length Nones
0    Ford    1.0     2.0   China     40  None
1    Ford    2.0     2.0  Mexico     50  None
2      VW    NaN     4.0  Mexico     30  None
3     BMW    2.0     2.0    None    NaN  None
4  Cooper    1.0     3.0   China     45  None
5  Cooper    1.0     NaN     NaN    NaT  None
6    None    NaN     NaN    None   None  None

In [79]:
df.isnull().any(axis=0)

Company    True
Stars      True
Weight     True
Origin     True
Length     True
Nones      True
dtype: bool

In [80]:
df.isnull().any(axis=1)

0    True
1    True
2    True
3    True
4    True
5    True
6    True
dtype: bool

#Drop the rows, if there is at  least one missing value

In [81]:
ndf1=df.copy()
ndf1.head()

  Company  Stars  Weight  Origin Length Nones
0    Ford    1.0     2.0   China     40  None
1    Ford    2.0     2.0  Mexico     50  None
2      VW    NaN     4.0  Mexico     30  None
3     BMW    2.0     2.0    None    NaN  None
4  Cooper    1.0     3.0   China     45  None

In [82]:
ndf1.dropna(inplace=True)

In [83]:
ndf1

Empty DataFrame
Columns: [Company, Stars, Weight, Origin, Length, Nones]
Index: []

In [84]:
ndf1.isnull().any().sum()

np.int64(0)

#Drop the columns, if there is at least one missing value

In [85]:
df.isnull().any()

Company    True
Stars      True
Weight     True
Origin     True
Length     True
Nones      True
dtype: bool

In [86]:
ndf2= df.copy()
ndf2= ndf2.dropna(axis=1)
ndf2.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

#Drop rows that have all null

In [87]:
ndf3=df.copy()
ndf3=ndf3.dropna(how="all")
ndf3

  Company  Stars  Weight  Origin Length Nones
0    Ford    1.0     2.0   China     40  None
1    Ford    2.0     2.0  Mexico     50  None
2      VW    NaN     4.0  Mexico     30  None
3     BMW    2.0     2.0    None    NaN  None
4  Cooper    1.0     3.0   China     45  None
5  Cooper    1.0     NaN     NaN    NaT  None

# Drop columns that have all null

In [88]:
ndf4=df.copy()
ndf4=ndf4.dropna(axis=1, how="all")
ndf4

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     2.0  Mexico     50
2      VW    NaN     4.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT
6    None    NaN     NaN    None   None

#Mantain Rows that have at least 4 values

In [89]:
ndf5=df.copy()
ndf5=ndf5.dropna(thresh=4,
                 )
ndf5

  Company  Stars  Weight  Origin Length Nones
0    Ford    1.0     2.0   China     40  None
1    Ford    2.0     2.0  Mexico     50  None
2      VW    NaN     4.0  Mexico     30  None
4  Cooper    1.0     3.0   China     45  None

#Mantain those columns that have at least 5 values

In [90]:
ndf6=df.copy()
ndf6.dropna(axis=1, thresh=5)
ndf6

  Company  Stars  Weight  Origin Length Nones
0    Ford    1.0     2.0   China     40  None
1    Ford    2.0     2.0  Mexico     50  None
2      VW    NaN     4.0  Mexico     30  None
3     BMW    2.0     2.0    None    NaN  None
4  Cooper    1.0     3.0   China     45  None
5  Cooper    1.0     NaN     NaN    NaT  None
6    None    NaN     NaN    None   None  None

#Replace numerical data with its meam

In [91]:
df.describe()

          Stars    Weight
count  5.000000  5.000000
mean   1.400000  2.600000
std    0.547723  0.894427
min    1.000000  2.000000
25%    1.000000  2.000000
50%    1.000000  2.000000
75%    2.000000  3.000000
max    2.000000  4.000000

In [92]:
sm=df.Stars.mean()
df["Stars"].fillna(sm, inplace=True)
df.Stars

/tmp/ipykernel_9044/4089342163.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Stars"].fillna(sm, inplace=True)

0    1.0
1    2.0
2    1.4
3    2.0
4    1.0
5    1.0
6    1.4
Name: Stars, dtype: float64

In [93]:
wm=df.Weight.mean()
df["Weight"].fillna(wm, inplace=True)
df.Weight

/tmp/ipykernel_9044/922527156.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Weight"].fillna(wm, inplace=True)

0    2.0
1    2.0
2    4.0
3    2.0
4    3.0
5    2.6
6    2.6
Name: Weight, dtype: float64

In [94]:
om=df.Origin.mode()[1]
om

'Mexico'

In [95]:
df["Origin"]=df.Origin.fillna(om)
df.Origin

0     China
1    Mexico
2    Mexico
3    Mexico
4     China
5    Mexico
6    Mexico
Name: Origin, dtype: object

In [96]:
df.isnull().any()

Company     True
Stars      False
Weight     False
Origin     False
Length      True
Nones       True
dtype: bool

In [97]:
df.dropna(how="all", inplace=True)
df

  Company  Stars  Weight  Origin Length Nones
0    Ford    1.0     2.0   China     40  None
1    Ford    2.0     2.0  Mexico     50  None
2      VW    1.4     4.0  Mexico     30  None
3     BMW    2.0     2.0  Mexico    NaN  None
4  Cooper    1.0     3.0   China     45  None
5  Cooper    1.0     2.6  Mexico    NaT  None
6    None    1.4     2.6  Mexico   None  None

In [98]:
df.dropna(how="all", axis=1, inplace=True)
df

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     2.0  Mexico     50
2      VW    1.4     4.0  Mexico     30
3     BMW    2.0     2.0  Mexico    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     2.6  Mexico    NaT
6    None    1.4     2.6  Mexico   None

In [100]:
cm=df.Company.mode()[0]
cm

'Cooper'

In [101]:
df["Company"]=df.Company.fillna(cm)
df.Company

0      Ford
1      Ford
2        VW
3       BMW
4    Cooper
5    Cooper
6    Cooper
Name: Company, dtype: object

In [103]:
lm=df.Length.mean()
df["Length"]=df.Length.fillna(lm)
df.isnull().any().sum()

np.int64(0)

#What is the average weight in Cars made in Mexico?

In [106]:
pd.pivot_table(
    df,
    index="Origin",
    aggfunc="mean",
    values="Weight"
)

        Weight
Origin
China     2.50
Mexico    2.64

#What is the average weight of ford cars in mexico?

In [117]:
pd.pivot_table(
    df,
    index="Origin",
    columns="Company",
    aggfunc="mean",
    values="Weight"
)

Company  BMW  Cooper  Ford   VW
Origin
China    NaN     3.0   2.0  NaN
Mexico   2.0     2.6   2.0  4.0