<a href="https://colab.research.google.com/github/ivannarch865/ivannarichards5to/blob/main/test01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. What data did we receive?

In [ ]:
file_path ="https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/Cartwheeldata.csv"
import pandas as pd
df= pd.read_csv(file_path)
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56,F,1,Y,1,62.0,61.0,79,Y,1,7
1,2,26,F,1,Y,1,62.0,60.0,70,Y,1,8
2,3,33,F,1,Y,1,66.0,64.0,85,Y,1,0
3,4,39,F,1,N,0,64.0,63.0,87,Y,1,10
4,5,27,M,2,N,0,73.0,75.0,72,N,0,4

- Age : is the age of each participant, it is a Numerical Value.

In [ ]:
df.Gender.unique()

array(['F', 'M'], dtype=object)

In [ ]:
df.GenderGroup.unique()

array([1, 2])

In [ ]:
df.shape

(25, 12)

In [ ]:
print("There are", df.shape[0], "rows")
print("There are", df.shape[1], "columns")

There are 25 rows
There are 12 columns

In [ ]:
print(*df.columns, sep="\n")

ID
Age
Gender
GenderGroup
Glasses
GlassesGroup
Height
Wingspan
CWDistance
Complete
CompleteGroup
Score

In [ ]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [ ]:
favs= ['Age', 'Gender', 'Glasses','Height', 'Wingspan', 'CWDistance',
       'Score']

In [ ]:
type(favs)

list

In [ ]:
ndf = df[favs]
ndf.head()

   Age Gender Glasses  Height  Wingspan  CWDistance  Score
0   56      F       Y    62.0      61.0          79      7
1   26      F       Y    62.0      60.0          70      8
2   33      F       Y    66.0      64.0          85      0
3   39      F       N    64.0      63.0          87     10
4   27      M       N    73.0      75.0          72      4

In [ ]:
ndf.dtypes

Age             int64
Gender         object
Glasses        object
Height        float64
Wingspan      float64
CWDistance      int64
Score           int64
dtype: object

In [ ]:
ndf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         25 non-null     int64
 1   Gender      25 non-null     object
 2   Glasses     25 non-null     object
 3   Height      25 non-null     float64
 4   Wingspan    25 non-null     float64
 5   CWDistance  25 non-null     int64
 6   Score       25 non-null     int64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.5+ KB

In [ ]:
ndf.describe()

             Age     Height   Wingspan  CWDistance      Score
count  25.000000  25.000000  25.000000   25.000000  25.000000
mean   28.240000  67.650000  66.260000   82.480000   6.120000
std     6.989754   4.431187   5.492647   15.058552   2.833137
min    22.000000  61.500000  57.500000   63.000000   0.000000
25%    24.000000  64.000000  62.000000   70.000000   4.000000
50%    26.000000  68.000000  66.000000   81.000000   6.000000
75%    29.000000  71.000000  71.000000   92.000000   8.000000
max    56.000000  75.000000  76.000000  115.000000  10.000000

In [ ]:
print("Age min", ndf.Age.min())
print("Age max", ndf.Age.max())
print("Age mean", ndf.Age.mean())
print("Age median", ndf.Age.median)
print("Age std", ndf.Age.std())

Age min 22
Age max 56
Age mean 28.24
Age median <bound method Series.median of 0     56
1     26
2     33
3     39
4     27
5     24
6     28
7     22
8     29
9     33
10    30
11    28
12    25
13    23
14    31
15    26
16    26
17    27
18    23
19    24
20    23
21    29
22    25
23    26
24    23
Name: Age, dtype: int64>
Age std 6.98975440674897

## 2. How do we inspect exactly rows and columns we need?

loc & iloc

df.loc[row_start_name:row_end_name, col_start_name:col_end_name]

df.iloc[row_start_int:row_end_int, col_start_int:col_end_int]

In [ ]:
ndf.columns

Index(['Age', 'Gender', 'Glasses', 'Height', 'Wingspan', 'CWDistance',
       'Score'],
      dtype='object')

2. 1 Choose First 4 column.

In [ ]:
ndf.loc[:, :"Height"]

    Age Gender Glasses  Height
0    56      F       Y   62.00
1    26      F       Y   62.00
2    33      F       Y   66.00
3    39      F       N   64.00
4    27      M       N   73.00
5    24      M       N   75.00
6    28      M       N   75.00
7    22      F       N   65.00
8    29      M       Y   74.00
9    33      F       Y   63.00
10   30      M       Y   69.50
11   28      F       Y   62.75
12   25      F       Y   65.00
13   23      F       N   61.50
14   31      M       Y   73.00
15   26      M       Y   71.00
16   26      F       N   61.50
17   27      M       N   66.00
18   23      M       Y   70.00
19   24      F       Y   68.00
20   23      M       Y   69.00
21   29      M       N   71.00
22   25      M       N   70.00
23   26      M       N   69.00
24   23      F       Y   65.00

In [ ]:
ndf.iloc[:, :4]

    Age Gender Glasses  Height
0    56      F       Y   62.00
1    26      F       Y   62.00
2    33      F       Y   66.00
3    39      F       N   64.00
4    27      M       N   73.00
5    24      M       N   75.00
6    28      M       N   75.00
7    22      F       N   65.00
8    29      M       Y   74.00
9    33      F       Y   63.00
10   30      M       Y   69.50
11   28      F       Y   62.75
12   25      F       Y   65.00
13   23      F       N   61.50
14   31      M       Y   73.00
15   26      M       Y   71.00
16   26      F       N   61.50
17   27      M       N   66.00
18   23      M       Y   70.00
19   24      F       Y   68.00
20   23      M       Y   69.00
21   29      M       N   71.00
22   25      M       N   70.00
23   26      M       N   69.00
24   23      F       Y   65.00

2.2 hoose the specfic cols "Age", "Gender", "Height", "CWDistance"

In [ ]:
favs2 = ["Age", "Gender", "Height", "CWDistance"]
ndf.loc[:, favs2]

    Age Gender  Height  CWDistance
0    56      F   62.00          79
1    26      F   62.00          70
2    33      F   66.00          85
3    39      F   64.00          87
4    27      M   73.00          72
5    24      M   75.00          81
6    28      M   75.00         107
7    22      F   65.00          98
8    29      M   74.00         106
9    33      F   63.00          65
10   30      M   69.50          96
11   28      F   62.75          79
12   25      F   65.00          92
13   23      F   61.50          66
14   31      M   73.00          72
15   26      M   71.00         115
16   26      F   61.50          90
17   27      M   66.00          74
18   23      M   70.00          64
19   24      F   68.00          85
20   23      M   69.00          66
21   29      M   71.00         101
22   25      M   70.00          82
23   26      M   69.00          63
24   23      F   65.00          67

In [ ]:
ndf.columns

Index(['Age', 'Gender', 'Glasses', 'Height', 'Wingspan', 'CWDistance',
       'Score'],
      dtype='object')

In [ ]:
favs3=[0,1,3,5]
ndf.iloc[:, favs3]

    Age Gender  Height  CWDistance
0    56      F   62.00          79
1    26      F   62.00          70
2    33      F   66.00          85
3    39      F   64.00          87
4    27      M   73.00          72
5    24      M   75.00          81
6    28      M   75.00         107
7    22      F   65.00          98
8    29      M   74.00         106
9    33      F   63.00          65
10   30      M   69.50          96
11   28      F   62.75          79
12   25      F   65.00          92
13   23      F   61.50          66
14   31      M   73.00          72
15   26      M   71.00         115
16   26      F   61.50          90
17   27      M   66.00          74
18   23      M   70.00          64
19   24      F   68.00          85
20   23      M   69.00          66
21   29      M   71.00         101
22   25      M   70.00          82
23   26      M   69.00          63
24   23      F   65.00          67

3. Rows Top 5

In [ ]:

ndf.iloc[:5, favs3]

   Age Gender  Height  CWDistance
0   56      F    62.0          79
1   26      F    62.0          70
2   33      F    66.0          85
3   39      F    64.0          87
4   27      M    73.0          72

Rows 5-10

In [ ]:
ndf.iloc[5:10, favs3]

   Age Gender  Height  CWDistance
5   24      M    75.0          81
6   28      M    75.0         107
7   22      F    65.0          98
8   29      M    74.0         106
9   33      F    63.0          65

Rows Bottom 5

In [ ]:
ndf.iloc[20:,favs3]

    Age Gender  Height  CWDistance
20   23      M    69.0          66
21   29      M    71.0         101
22   25      M    70.0          82
23   26      M    69.0          63
24   23      F    65.0          67

In [ ]:
ndf.iloc[-5:, favs3]

    Age Gender  Height  CWDistance
20   23      M    69.0          66
21   29      M    71.0         101
22   25      M    70.0          82
23   26      M    69.0          63
24   23      F    65.0          67

Top 5 LOC

In [ ]:
ndf.loc[:4, favs2]

   Age Gender  Height  CWDistance
0   56      F    62.0          79
1   26      F    62.0          70
2   33      F    66.0          85
3   39      F    64.0          87
4   27      M    73.0          72

5-10 LOC

In [ ]:
ndf.loc[5:9, favs2]

   Age Gender  Height  CWDistance
5   24      M    75.0          81
6   28      M    75.0         107
7   22      F    65.0          98
8   29      M    74.0         106
9   33      F    63.0          65

Bottom 5 LOC

In [ ]:
ndf.loc[20:, favs2]

    Age Gender  Height  CWDistance
20   23      M    69.0          66
21   29      M    71.0         101
22   25      M    70.0          82
23   26      M    69.0          63
24   23      F    65.0          67

How do

In [ ]:
df.Gender.unique()
df.Gender.nunique()

2

In [ ]:
df.GenderGroup[0]

np.int64(1)

-"Gender": Explains Gender of each participant, categories are ["F", "M"]
- "GenderGroup": Also categroical variable but it shows numerical variable. We have to convert to Categorical variable.

In [ ]:
df["GenderGroup"] = df.GenderGroup.astype("str")
df.GenderGroup[0]

'1'

In [ ]:
df.iloc[:, 2:4]

   Gender GenderGroup
0       F           1
1       F           1
2       F           1
3       F           1
4       M           2
5       M           2
6       M           2
7       F           1
8       M           2
9       F           1
10      M           2
11      F           1
12      F           1
13      F           1
14      M           2
15      M           2
16      F           1
17      M           2
18      M           2
19      F           1
20      M           2
21      M           2
22      M           2
23      M           2
24      F           1

In [ ]:
favs=["Gender", "GenderGroup"]
df[favs].value_counts()

Gender  GenderGroup
M       2              13
F       1              12
Name: count, dtype: int64

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56,F,1,Y,1,62.0,61.0,79,Y,1,7
1,2,26,F,1,Y,1,62.0,60.0,70,Y,1,8
2,3,33,F,1,Y,1,66.0,64.0,85,Y,1,0
3,4,39,F,1,N,0,64.0,63.0,87,Y,1,10
4,5,27,M,2,N,0,73.0,75.0,72,N,0,4

(25, 12)

In [ ]:
favs.loc[:, -1:]

NameError: name 'favs' is not defined